### ISSUE TITLE
watch father file of includes

### ISSUE THREAD

**Issue by acidjazz** [jadejs/jade#1086]
I have to use jade command-line mostly because of other languages I have to use for my current line of work (same with stylus).  One feature I would love is for if I'm watching say "index.jade" is for jade to re-compile upon the write of any included file say "_header.jade" or even extension related to index.jade. I noticed stylus does this and I'd love to not have to re-compile jade every time I modify an include.

Thanks!

**Comment by jayliu50** [comment]
@ForbesLindesay could you provide an example of accessing the list of dependencies, please?

Also, are you suggesting that jade watch doesn't recompile extended and included files, by design? For example, I have `page.jade` which extends `layout.jade`. When I made a change to `layout.jade`, `layout.html` is updated, but not `page.html`.

**Comment by TimothyGu** [comment]
@jayliu50 In the latest version of [jade-cli](https://www.npmjs.org/package/jade-cli) everything works as expected, i.e. while `jade -w page.jade` is running, if `layout.jade` is changed `page.html` is updated. OTOH, when you do `jade -w page.jade layout.jade`, when `layout.jade` is changed both HTMLs are updated.

**Comment by jayliu50** [comment]
@TimothyGu Thanks for the response. Yes, it does work. I found out that jade was resolving to an old copy of 1.7 for some reason.
