### ISSUE TITLE
fighting inline-block spacing through comments

### ISSUE THREAD

**Issue by niwann** [jadejs/jade#1574]
in straight html you can fight spacing between inline-block elements by "glueing" them together with comments. like this:
```html
    <ul>
      <li>one</li><!--
      --><li>two</li><!--
      --><li>three</li>
    </ul>
```
Unfortunately i didn't find a way to do exactly that in jade. (except of course minifying/uglifying the whole document, which is not allways what you would want.)

**Comment by duckinator** [comment]
So, I just ran into this problem, and found both this issue and some documentation on _Scala's_ Jade: http://scalate.github.io/scalate/documentation/jade-syntax.html#Whitespace_Removal:__code__gt___code__and__code__lt___code_

> \> and < give you more control over the whitespace near a tag. > will remove all whitespace surrounding a tag, while < will remove all whitespace immediately within a tag. You can think of them as alligators eating the whitespace: > faces out of the tag and eats the whitespace on the outside, and < faces into the tag and eats the whitespace on the inside. They're placed at the end of a tag definition, after class, id, and attribute declarations but before / or =.

If I am reading that description correctly, then this:

```
ul
  li> one
  li> two
  li> three
```

becomes:

```
<ul><li>one</li><li>two</li><li>three</li></ul>
```

Trying to figure out which elements are inline and which aren't isn't even technically possible from Jade alone, since it can be changed with CSS. You could _at best_ determine which elements are inline _by default_. You would be screwed for anything you set to inline (thus making whitespace significant) via CSS.

This avoids that problem entirely, but does not force you to use plain HTML (where the solutions are all rather gross hacks, or entirely removing whitespace).

While it _does_ add complexity to the language itself (and, due to that, the implementation), the approach they took for the Scala implementation feels like the most reasonable solution, to me.

**Comment by duckinator** [comment]
As a note, this could likely be handled in a similar manner to blocks of text: http://jade-lang.com/reference/plain-text/

```jade
script.
  if (usingJade)
    console.log('you are awesome')
  else
    console.log('use jade')
```

**Comment by ForbesLindesay** [comment]
Closing this as the idea should be tracked along with #1123

**Comment by TimothyGu** [comment]
Also see #1833.

**Comment by TimothyGu** [comment]
For others trying to use a workaround, this works fine:

```jade
ul
  li
    blah
    | </li><li>
    blah
    | </li><li>
    blah
```
