### ISSUE TITLE
Reverse of #{}

### ISSUE THREAD

**Issue by jacobp100** [jadejs/jade#1813]
`#{}` evaluates code when there's non-code entry. How about `${}` to evaluate jade when there's code entry.
 
E.g.
```
script.
   var x = 3;
   var y = '${p.test Test}'
```

**Comment by jacobp100** [comment]
As an alternative to #1812

**Comment by TimothyGu** [comment]
Sorry but I do not understand what the problem is here. What is your expected HTML output?

Doesn't this meet your standards?

```jade
script.
  var x = 3;
  var y = '#{p.test} Test'
```

**Comment by vendethiel** [comment]
I think you're looking for #[]

**Comment by ForbesLindesay** [comment]
```jade
script.
   var x = 3;
   var y = '#[p.test Test]'
```

does exactly what you're after.

**Comment by jacobp100** [comment]
Thanks!

**Comment by jacobp100** [comment]
How would I go about manipulating this? E.g. Escaping quotes as follows:
```jade
var y = "#[p.test Test].replace('\"', '\\"')"
```

**Comment by TimothyGu** [comment]
```jade
var y = "#[p.test Test]".replace('\"', '\\"')
```

should suffice.

**Comment by ForbesLindesay** [comment]
@TimothyGu I don't think that will work as intended.  I think the short answer is that there is no easy syntax for it.  You will have to use single quotes `'` outside the jade (because jade uses double quotes `"` internally) and then be sure to escape any occurrences of single quotes inside the template.  In short, it's not really a supported use case.

**Comment by TimothyGu** [comment]
^^ True.
