### ISSUE TITLE
escaping single quote characters

### ISSUE THREAD

**Issue by pateljatin** [jadejs/jade#1841]
Hi,

hi - does anyone know how to properly escape single quote chars for ga (google analytics) events within jade code?
for e.g. following:
```
button.btn.newbuy.color(id='customButton', onClick="ga('send', 'event', 'Buy Button', 'click', 'Buy Action button Clicked', {'page': '#{locals.eventData.eventName}'});")
```
the #{locals.eventData.eventName} has a string value with an apostrophe such as: <b>Jatin's train</b>
i'm using jade 0.30.0 - i cant update the lib to latest as lot of templates will break due to changes after v0.30 - unless I really need to use latest for this fix?

Thanks,
JP

**Comment by TimothyGu** [comment]
We don't support old releases. Update your templates please.

**Comment by pateljatin** [comment]
that's ok - that seemed like a corporate answer :)
no worries - I was able to fix this issue - BTW: the issue occurs also with the latest release.
here's how I fixed it -  bit of simple stuff:
```
button.btn.newbuy.color(id='customButton', onClick="ga('send', 'event', 'Buy Button', 'click', 'Buy Action button Clicked', {'page': '" + locals.eventData.eventName + "'});")
```
In case somebody stumbles upon this, they can look at the solution here.

Thanks,
JP

**Comment by TimothyGu** [comment]
You do have to realize that 0.30.0 was released almost 2 years ago. No projects would ever support 2-year-old releases. Plus Jade doesn't have the concept of concurrent release branches, so even if we do support 2-year-old releases we can't fix any bugs in it.

**Comment by ForbesLindesay** [comment]
The issue @pateljatin I plan to support 1.x.y for at least the first 6 months or so after 2.0.0 is released, but only patching really major bugs (pretty much just security critical bugs).  0.x.y is so old now that it's really not manageable, and the code base back then was extremely buggy.  I really wouldn't recommend it in production.

As an aside, both the examples you give produce the exact same result using the latest version of jade.

```jade
- locals.eventData = {eventName: 'foo'}
button.btn.newbuy.color(id='customButton', onClick="ga('send', 'event', 'Buy Button', 'click', 'Buy Action button Clicked', {'page': '#{locals.eventData.eventName}'});")
button.btn.newbuy.color(id='customButton', onClick="ga('send', 'event', 'Buy Button', 'click', 'Buy Action button Clicked', {'page': '" + locals.eventData.eventName + "'});")
```

```html
<button id="customButton" onClick="ga('send', 'event', 'Buy Button', 'click', 'Buy Action button Clicked', {'page': 'foo'});" class="btn newbuy color"></button>
<button id="customButton" onClick="ga('send', 'event', 'Buy Button', 'click', 'Buy Action button Clicked', {'page': 'foo'});" class="btn newbuy color"></button>
```

If there ever was a bug, it's fixed now.  In general it is preferable to use standard JavaScript syntax in attribute values rather than the interpolation syntax anyway.  It's simpler and easier to understand.

**Comment by BarnabasSzabolcs** [comment]
How are single quotes escaped in the latest version of pug?
