### ISSUE TITLE
Extend path with variables

### ISSUE THREAD

**Issue by thenitai** [jadejs/jade#1900]
Hi all,

I'm currently working on a complete "Theme" setup for our application. However, today I run into a show stopper, that is that I wasn't able to use the extend, include, etc. tags with variables.

Something like this doesn't work:

```
extends layouts/#{theme}/main
```

Is there any way to make this work?

**Comment by TimothyGu** [comment]
Nope. See:

- #366
- #416
- #520
- #569 
- #817
- #839 
- #843 
- #1312
- #1433 
- #1481 
- #1893
- and many many others…

Please search closed tickets before opening new ones.

**Comment by brwnll** [comment]
The team seems pretty aggro about this topic, likely because of the number of times it's been asked. But that just means this should be included in the docs/README, instead of expecting the numerous people who have had this issue to completely read each of the 28 issue threads that a search turns up (most of which say "discussed elsewhere", sometimes followed by further discussion)
