### ISSUE TITLE
why doesn't extends look for files in 'views' array?

### ISSUE THREAD

**Issue by btknorr** [jadejs/jade#1932]
Express 4 let's you set multiple folders to the views option:

```javascript
app.set('views', [
                   path.join(__dirname, 'views'),
                   path.join(__dirname, 'node_modules/module1/views'),
                   path.join(__dirname, 'node_modules/base/layouts'),
]);
```

But when I try to extend a jade file located in one of node_modules paths, it fails to find it.  Why is that?  Is there not support for multiple locations for basedir?  Does basedir even look at the set 'views'?  Also we would like to avoid doing something like 'extends ../.../../node_modules/base/layouts/default.jade'

Thoughts?

Thanks,

Brian

**Comment by TimothyGu** [comment]
I don't think Jade is able to access the array, which is stored in Express. Currently it just searches the same directory the original file is in.

**Comment by ForbesLindesay** [comment]
jade and express aren't especially tightly coupled, so basedir doesn't even use that input at all.  We purposefully only support a single basedir because that makes it much easier to find dependencies when reading code.  Remember that code is read far more often than it is written.

There is some talk elsewhere of supporting an node/npm style path resolution algorithm, which I would be keen to consider.  In 2.0.0 it should be possible to override the path resolution algorithm to do whatever you choose.
