### ISSUE TITLE
inline comments

### ISSUE THREAD

**Issue by avalanche1** [jadejs/jade#1978]
It would be nice to have inline comments, like this
`p foo //bar`

**Comment by drulia** [comment]
I agree, I would like that as well

**Comment by ForbesLindesay** [comment]
I think this would be far too confusing in general because it would make it very difficult to have something that outputted `<p>foo //bar</p>`.  We could probably support something like this for if/else if/else and case/when though.

**Comment by avalanche1** [comment]
I think it'd be more confusing if conditionals supported inline comments and everything else didn't)
What's the prob with escaping '/' in plain text?

**Comment by drulia** [comment]
just to clarify, I agree that `<p>foo //bar</p>` would be confusing. I was really referring to comments that are not preserved in the output html, i.e. `p foo //- bar` when I've said that I would like that.

**Comment by avalanche1** [comment]
@drulia  yep, me too

**Comment by TimothyGu** [comment]
How about `<p>foo //- bar</p>` then?

**Comment by ForbesLindesay** [comment]
Inline comments don't make sense in a whitespace sensitive language where many lines can end in an arbitrary string.

**Comment by JonatasArcode** [comment]
To get a usefull info to those searching this, there's a **not good looking** solution here if you really want it (at end line only):

`element text #{ _ /* comment */}`

it does compile, and don't place any undesired charater on your HTML

since the `#{ }` block evalueates a Javascript expression, you can put a normal JS comment in there `/* */`
the `_` evaluates to undefined (a variable that doesn't exist, if you didn't declare it, of course), and is the "1st variable name's safe char" that has the minimal visual impact on code (besides whats #{} already does)
