### ISSUE TITLE
Inline CoffeeScript code instead of javascript

### ISSUE THREAD

**Issue by eugene-piatenko** [jadejs/jade#2023]
Hi!
You have a nice filter :coffee-script
It works file, but always compiles as a string of javascript text in output.
I would be VERY useful to add something to let :coffee-script filter work as inline interpolated code.
For example
```jade
-
  :coffee-script
    #coffeescript code
    min = (x,y) -> if x<y then x else y
```

it should be not complicated to do...

Thanks!

**Comment by ForbesLindesay** [comment]
No, jade will never support coffee script other than within filters.  JavaScript is much easier to read, and your code will be read far more times than it is written.  We will work towards adding ES6 support as soon as we can.

**Comment by eugene-piatenko** [comment]
>> JavaScript is much easier to read, and your code will be read far more times than it is written. 

That's only your opinion, it's not true.

Why to restrict people to use it? Just because "I want"?

Strange position...
Let people use it if they want.

I could understand answer "it's hard to do it", or, "it does not fit to our parser structure", or, "it will take more time to implement and it's not so important".... anything...
but... "JavaScript is much easier to read" - funny )

**Comment by ForbesLindesay** [comment]
All those things are also obviously true, but I wouldn't mind solving hard problems if there was real gain to be had at the end of all that.  There isn't though.  You are free to fork jade and add coffee script.  I think others probably already have.

I'm being brief because this has been discussed many times already in this issue tracker.
