### ISSUE TITLE
Comments in script node throw an Error.

### ISSUE THREAD

**Issue by zhoukekestar** [jadejs/jade#2089]
![test](https://cloud.githubusercontent.com/assets/7157346/9870455/8f8d8ce6-5bbe-11e5-91d8-f178147b572b.gif)

**Comment by ForbesLindesay** [comment]
This is expected behaviour.  The comment is no longer a jade comment once you put it inside the `script.` tag because the `.` indicates that the contents of the tag are plain text.  This means that it is just a JavaScript comment.  Jade evaluates the interpolation anywhere inside plain text, hence the error.  We don't evaluate anything inside a jade comment though, even interpolation.
