### ISSUE TITLE
relative path in scss includes

### ISSUE THREAD

**Issue by episodeyang** [jadejs/jade#2161]
Hi,

I'm running into a problem with the @import inside included :scss files.

It looks like if I have the following files:

### first-app/index.jade
```jade
include:scss ./index.scss
```

### first-app/index.scss: 
```scss
@import './../components/style-mixins/mixins.scss'
```

### /components/style-mixins/mixins.scss
```
some scss text

```

jade gives an error message on module.exports.readerSync.

this does not happen when I just use node-sass to compile the files, or compile the files with gulp-sass

https://github.com/jstransformers/jstransformer-scss/issues/7

**Comment by ForbesLindesay** [comment]
This is because jade@1 calls `jstransformer.render` which only works if the transformer happens to accept a `filename` option.  jade@2 will call `jstransformer.renderFile` and pass the correct filename.

**Comment by Robert-W** [comment]
Any idea when when this will be released? I am using gulp-pug to compile my templates and it is having the same issue, I checked it's `package.json` and it is using pug `2.0.0-alpha6`

**Comment by ForbesLindesay** [comment]
This should be working now.  If you can provide a small test case that reproduces the error with `2.0.0-beta3` then please open a new issue.

**Comment by Robert-W** [comment]
Thanks.  I have since found a slightly different workflow to achieve the same end result.  I did try to change the dependency in gulp-pug to `2.0.0-beta3` and saw the same results.  If I go back to this method, I will test on an isolated case and submit a new ticket if the issue is still happening.  It may also be an issue with the implementation in `gulp-pug` or `jstransformer-sass`.
